### ISSUE TITLE
Agregar tabla de leyendas para la consulta de Plan de Estudios

### ISSUE THREAD

**Issue by wolfogan** [wolfogan/sigaf#54]
Azul - Tronco Común
Gris Claro - Optativa
Verde Claro - Etapa Básica
Mamey - Etapa Disciplinaria
Naranja - Etapa Terminal

**Comment by tyntia** [comment]
Queda pendiente un color, el de eetapa disciplinaria

**Comment by wolfogan** [comment]
Cuando termines, cierras el issue y le pones el commit donde se encuentra la tabla pls thanks :D

**Comment by tyntia** [comment]
completado, commit: 0a74d2aa79081bff0bba62b32b4f03c6dade72db
